Fix cordova cannot find symbol build failed error.
Cordova ant Build failed because FileNotFoundException class wasn't imported.
platforms/android/src/org/apache/cordova/Zip.java:55: error: cannot find symbol.